[versions]
kotest = "6.0.3"
selenide = "7.12.0"
springBoot = "3.5.7"
testcontainersKeycloak = "3.9.0"

[libraries]
apache-http-client = { group = "org.apache.httpcomponents.client5", name = "httpclient5" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-spring = { group = "io.kotest", name = "kotest-extensions-spring", version.ref = "kotest" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor" }
reactor-core = { group = "io.projectreactor", name = "reactor-core" }
selenide = { group = "com.codeborne", name = "selenide", version.ref = "selenide" }
spring-boot-dependencies = { group = "org.springframework.boot",  name = "spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-starter-oauth2-client = { group = "org.springframework.boot", name = "spring-boot-starter-oauth2-client" }
spring-boot-starter-oauth2-resource-server = { group = "org.springframework.boot", name = "spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-security-core = { group = "org.springframework.security", name = "spring-security-core" }
spring-web = { group = "org.springframework", name = "spring-web" }
testcontainers-keycloak = { group = "com.github.dasniko", name = "testcontainers-keycloak", version.ref = "testcontainersKeycloak" }

[bundles]
kotest = ["kotest-assertions", "kotest-property", "kotest-runner-junit5", "kotest-spring"]
